export const VIDEO_SUCCESS = "VIDEO_SUCCESS";
export const UPDATE_STATUS="UPDATE_STATUS"
export const UPDATE_ALLSTATUS="UPDATE_ALLSTATUS"
export const DELETE_VEDIO="DELETE_VEDIO"
export const COPY_VEDIO="COPY_VEDIO"
export const LAST_CREATED="LAST_CREATED"
export const LAST_MODIFIED="LAST_MODIFIED"