export let GET_PROJECTS_LOADING="GET_PROJECTS_LOADING"
export let GET_PROJECTS_SUCESS="GET_PROJECTS_SUCESS"
export let GET_PROJECTS_ERROR="GET_PROJECTS_ERROR"

export let ADD_PROJECTS_LOADING="ADD_PROJECTS_LOADING"
export let ADD_PROJECTS_SUCESS="ADD_PROJECTS_SUCESS"
export let ADD_PROJECTS_ERROR="ADD_PROJECTS_ERROR"

export let DELETE_PROJECTS_LOADING="DELETE_PROJECTS_LOADING"
export let DELETE_PROJECTS_SUCESS="DELETE_PROJECTS_SUCESS"
export let DELETE_PROJECTS_ERROR="DELETE_PROJECTS_ERROR"